apps:
  - ./apps/sinatra
  - ./apps/bun

state_dir: ./state
log_dir: ./log
socket: ./deploy-boss.sock

proxy:
  listen: 127.0.0.1:8080

management:
  listen: 127.0.0.1:8081
  host: boss.lvh.me
  auth:
    realm: auth.authcog.com
    admin_emails:
      - rejotl@gmail.com
    session_ttl: 24h

ports:
  range: [3100, 3199]

defaults:
  idle_stop: 0s
